import os
def DisplayGraphics():
    os.system('clear')
    #path = os.getcwd()
    print('\033[92m'+"\n       8                      o                      8                   ")
    print("       8                      8                      8                   ")
    print("       8oPYo. o    o .oPYo.  o8P oPYo. .oPYo. .oPYo. 8  .o  .oPYo. oPYo. ")
    print("       8    8 8    8 8    8   8  8  `' .oooo8 8    ' 8oP'   8oooo8 8  `' ")
    print("       8    8 8    8 8    8   8  8     8    8 8    . 8 `b.  8.     8     ")
    print("       `YooP' `YooP' `YooP8   8  8     `YooP8 `YooP' 8  `o. `Yooo' 8     ")
    print("       :.....::.....::....8 ::..:..:::::.....::.....:..::...:.....:..::::")
    print("       ::::::::::::::::ooP'.:::::::::::::::::::::::::::::::::::::::::::::")
    print("       ::::::::::::::::...:::::::::::::::::::::::::::::::::::::::::::::::")
    print("                                              ")
    print("                                         8  o ")
    print("                                         8    ")
    print("                                  .oPYo. 8 o8 ")
    print("                                  8    ' 8  8 ")
    print("                                  8    . 8  8 ")
    print("                                  `YooP' 8  8 ")
    print("                                  :.....:..:..")
    print("                                  ::::::::::::")
    print("                                  ::::::::::::\n\n")
    print("BUGTRACKER-CLI v1.0\n"+'\033[0m')